### ISSUE TITLE
Zugang zu Admin-Funktionen

### ISSUE THREAD

**Issue by exwima** [UB-Mannheim/MArs#24]
Die Admin-Funktionen waren bei einer Testinstallation auch mit normaler Anmeldung zugänglich. $master war einfach bei jeder erfolgreichen Anmeldung "true". 
Vermutete Ursache: automatische Typkonversion beim Vergleich von Boolean mit String.

aus index.php:
```
// Should admin commands be allowed
$master = ($authorized && $authorized == 'master');
```
Korrekturvorschlag:  
`$master = ($authorized === 'master');`

**Comment by stweil** [comment]
Thank you for the hint and for the right fix. Do you want to send a pull request which fixes the code?

The code works for us because our `config.php` does not return `true`, but one of `false`, `"user"` or `"master"`.
