### ISSUE TITLE
Restrict admin access

### ISSUE THREAD

**Issue by dennmuel** [UB-Mannheim/MArs#3]
Using ldap, alma, ip?

**Comment by stweil** [comment]
Currently admin access for booking and enhanced functions is restricted to users which use the master password. Maybe this is sufficient.

Restricting the allowed IP addresses could further improve the security.

Using the `staff` attribute would require additional input: real uid + target uid, resulting in higher code complexity. Maybe this can be avoided.

**Comment by dennmuel** [comment]
Well, if you find the current state (and optionally IP address) sufficient, we can close this. I pulled this from an internal text file that seemed to be outdated / unclear.

**Comment by stweil** [comment]
IP is now restricted to university subnet.
