### ISSUE TITLE
Confirmation mails

### ISSUE THREAD

**Issue by dennmuel** [UB-Mannheim/MArs#9]
Make confirmation mails opt-in. Only send them to mail-routing-address.

**Comment by stweil** [comment]
Implemented in commit dcbbc78dfde40dcb0e3e0f5edd119fbbf6769d3c. Please review and test, then close this issue.

**Comment by dennmuel** [comment]
The email I received contained a booking I don't have, see below:

Date       Location
2020-06-03 Bibliotheksbereich Ehrenhof
2020-06-16 Bibliotheksbereich Ehrenhof

![grafik](https://user-images.githubusercontent.com/21078769/83618243-78dc6100-a58a-11ea-96f4-674bfbf786b6.png)

**Comment by dennmuel** [comment]
Update: It disappeared when cancelling the one actual reservation. But we'll need to change the mail text for the case when there are no active booking:

"Sie haben über unser Buchungssystem eine E-Mail-Benachrichtigung angefordert.

text

Informieren Sie sich vor Ihrem Besuch bitte über die Hygieneregeln in den Bibliotheksbereichen:
https://www.bib.uni-mannheim.de/corona/teiloeffnung-der-bibliotheksbereiche/"

**Comment by dennmuel** [comment]
Sorry to flood this, but on booking new reservations, I also received the mail with "text" and no booking list at all.

**Comment by stweil** [comment]
That was a bug (`text` instead of `$text` in PHP code) which is fixed now.
